image: golang:latest
stages:
  - deploy
before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass
  - go get gopkg.in/yaml.v3
  - mkdir -p $(pwd)/build

deploy-dev:
  stage: deploy  
  script:
    - cd $(pwd)/src
    - go build -race -ldflags "-extldflags '-static'" -o $(pwd)/build/main
    - mv $(pwd)/build/main $(pwd)/build/autoconf-nginx
    - export SSHPASS=$USER_PSWD
    - sshpass -e scp -P36702 -o StrictHostKeyChecking=no -r $(pwd)/build/ $USER_NAME@$SERVER_NAME:~/tools
  only:
    - master

